# DO NOT CHANGE THIS FILE DIRECTLY
# Source: https://github.com/schubergphilis/mcaf-github-workflows
default_stages: [pre-commit]
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.104.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
      - id: terraform_validate
  - repo: https://github.com/bridgecrewio/checkov
    rev: "3.2.495"
    hooks:
      - id: checkov
        language_version: python3.11
        args:
          - --download-external-modules=true
          - --quiet
          - --compact
          # (optional) limit frameworks to Terraform only:
          - --framework
          - terraform
          # skip specific checks (comma-separated)
          - --skip-check=CKV_GIT_5,CKV_GLB_1,CKV_TF_1
          # skip a path (quote or keep on one line)
          - --skip-path=examples/*
        additional_dependencies:
          - pycares<5.0
